### ISSUE TITLE
Let's call this test and class more specific to its purpose 

### ISSUE THREAD

**Issue by katiholasz** [seby223/POM#3]
https://github.com/seby223/POM/blob/2c7dc891536e7e1109b7958e848dc5ece3cbb6b2/POM/Tests/SystemTest.cs#L8

**Comment by seby223** [comment]
Changed the name of the class and the test. Please see if it's acceptable.

**Comment by katiholasz** [comment]
> Changed the name of the class and the test. Please see if it's acceptable.
looks good :D thanks
